services:
  - type: web
    name: 3-kart-tiktok-bridge
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TIKTOK_USERNAME
        sync: false
      - key: GIFT_NAME
        value: parfüm
      - key: MAX_PLAYERS
        value: "12"
